name: Generator

on:
  schedule:
    # Run  Monday/Wednesday 5pm
     - cron: '0 0 * * 2,4'
    #- cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Generate SoftLayer classes
      run: |
        make generate
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff -s --exit-code; if [ "$?" -ne 0 ]; then git commit -m "Updated generated classes on `date`" -a; fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
